/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useAnimations } from '@react-three/drei';
import { useRef, useEffect } from 'react';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/shuffling.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.shuffling.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Peasant_girl.geometry}
          material={materials.Peasant_Girl}
          skeleton={nodes.Peasant_girl.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/shuffling.glb');
